services:
  app:
    container_name: steam-platinum-tracker-app
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: "file:/data/app.db"
    volumes:
      - ./web:/app
      - ./data:/data
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped